common:
  frame_id: "lili_om_rot"
  data_set: "drz"
  
IMU:
  acc_n: 2000
  gyr_n: 0.0173
  acc_w: 2
  gyr_w: 0.00025

preprocessing:
  lidar_topic: "/os_cloud_node/points"
  ds_rate: 4
  line_num: 128

lidar_odometry:
  max_num_iter: 12
  scan_match_cnt: 1
  if_to_deskew: false

backend_fusion:
  max_num_iter: 15
  loop_closure_on: true
  local_map_width: 50
  lc_search_radius: 15
  lc_map_width: 25
  lc_icp_thres: 0.2
  slide_window_width: 3
  imu_topic: "/dji_sdk/imu"
  lidar_const: 7.5
  mapping_interval: 2
  lc_time_thres: 60.0
  surf_dist_thres: 0.12
  kd_max_radius: 1.0
  save_pcd: false

#extrinsic imu to lidar
  ql2b_w: 0.0247437
  ql2b_x: 0.706674
  ql2b_y: -0.706674
  ql2b_z: 0.0247437
  tl2b_x: 0.101775
  tl2b_y: -0.006253
  tl2b_z: -0.217645
